// <auto-generated />
using CodeFirstPracticeUpdates.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstPracticeUpdates.Migrations
{
    [DbContext(typeof(ShelfContext))]
    [Migration("20201101231344_ChangedMaterialTypes")]
    partial class ChangedMaterialTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstPracticeUpdates.Models.Shelf", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ShelfMaterialID")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.HasIndex("ShelfMaterialID")
                        .HasName("FK_Shelf_Shelf_Material");

                    b.ToTable("shelfs");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Item1",
                            ShelfMaterialID = 1
                        },
                        new
                        {
                            ID = -2,
                            Name = "Item2",
                            ShelfMaterialID = 2
                        },
                        new
                        {
                            ID = -3,
                            Name = "Item3",
                            ShelfMaterialID = 3
                        },
                        new
                        {
                            ID = -4,
                            Name = "Item4",
                            ShelfMaterialID = 4
                        },
                        new
                        {
                            ID = -5,
                            Name = "Item5",
                            ShelfMaterialID = 5
                        });
                });

            modelBuilder.Entity("CodeFirstPracticeUpdates.Models.Shelf_Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("MaterialName")
                        .HasColumnType("varchar(25)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("shelf_material");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MaterialName = "wood"
                        },
                        new
                        {
                            ID = 2,
                            MaterialName = "glass"
                        },
                        new
                        {
                            ID = 3,
                            MaterialName = "rubber"
                        },
                        new
                        {
                            ID = 4,
                            MaterialName = "steel"
                        },
                        new
                        {
                            ID = 5,
                            MaterialName = "plastic"
                        });
                });

            modelBuilder.Entity("CodeFirstPracticeUpdates.Models.Shelf", b =>
                {
                    b.HasOne("CodeFirstPracticeUpdates.Models.Shelf_Material", "ShelfMaterial")
                        .WithMany("Shelfs")
                        .HasForeignKey("ShelfMaterialID")
                        .HasConstraintName("FK_Shelf_Shelf_Material")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
